### PR TITLE
[Security Solution][Investigations] - Integrate details flyout with session view

### PR DESCRIPTION
**Pull request by michaelolo24**
## Summary

Based on this PR: https://github.com/elastic/kibana/pull/127991

This PR introduces the ability to be able to open the alert details flyout from the session view component. It also provides users the ability to change the status of the alert from the flyout and see that change reflected within the session viewer. There is a bug with the session viewer currently where changing the status of the same alert back to back doesn't cause the expected change in the session viewer alert status the second time, but that will be fixed in a separate PR.

https://user-images.githubusercontent.com/17211684/159709348-07b85189-5ec1-441c-9e47-8540d01fabec.mov

### Checklist

Delete any items that are not applicable to this PR.

- [x] [Unit or functional tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html) were updated or added to match the most common scenarios

### CODE REVIEW

**Comment by kqualters-elastic** [comment]
lgtm + will be reviewed as the whole thing, merging 👍

**Comment by michaelolo24** [comment]
Accidentally pushed main in my branch, will create a new one

**Comment by michaelolo24** [comment]
or undo that commit rather

**Comment by kqualters-elastic** [comment]
image

**Pull request merged**
